<?php
/**
 * لوگو: لوگوی آپلودشده در «سفارشی‌سازی ← هویت سایت» یا لوگوی متنی پیش‌فرض.
 *
 * @package TechnoPay
 */

defined( 'ABSPATH' ) || exit;

if ( has_custom_logo() ) {
	// فقط خود لوگو (بدون آیکون و نام سایت). نسخهٔ تاریک (اختیاری) در حالت تاریک جایگزین می‌شود.
	$technopay_logo      = get_custom_logo();
	$technopay_logo_dark = (int) technopay_option( 'logo_dark' );
	$technopay_link_cls  = array();
	if ( $technopay_logo_dark && wp_attachment_is_image( $technopay_logo_dark ) ) {
		$technopay_dark_img = wp_get_attachment_image(
			$technopay_logo_dark,
			'full',
			false,
			array(
				'class' => 'custom-logo custom-logo--dark',
				'alt'   => get_bloginfo( 'name' ),
			)
		);
		if ( '' !== $technopay_dark_img ) {
			$technopay_logo       = preg_replace( '#</a>\s*$#', $technopay_dark_img . '</a>', $technopay_logo );
			$technopay_link_cls[] = 'has-dark-logo';
		}
	}
	if ( technopay_option( 'logo_invert_dark' ) && ! $technopay_link_cls ) {
		$technopay_link_cls[] = 'logo-invert-dark';
	}
	if ( $technopay_link_cls ) {
		$technopay_logo = str_replace( 'class="custom-logo-link"', 'class="custom-logo-link ' . esc_attr( implode( ' ', $technopay_link_cls ) ) . '"', $technopay_logo );
	}
	echo $technopay_logo; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- markup generated by WordPress core.
	return;
}
?>
<a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="logo" rel="home">
	<span class="logo__mark" aria-hidden="true"><?php technopay_icon( 'logo' ); ?></span>
	<span class="logo__text">
		<span class="logo__name"><?php bloginfo( 'name' ); ?></span>
		<?php if ( technopay_option( 'logo_tagline' ) ) : ?>
			<span class="logo__tag"><?php echo esc_html( technopay_option( 'logo_tagline' ) ); ?></span>
		<?php endif; ?>
	</span>
</a>
